# Школа глубокого обучения

<a href="https://mipt.ru/science/labs/laboratoriya-neyronnykh-sistem-i-glubokogo-obucheniya/"><img align="right" src="https://avatars1.githubusercontent.com/u/29918795?v=4&s=200" alt="DeepHackLab" style="position:relative;top:-40px;right:10px;height:100px;" /></a>



### Физтех-Школа Прикладной математики и информатики МФТИ 
### Лаборатория нейронных сетей и глубокого обучения (DeepHackLab)

## Занятие 1. Библиотека Numpy

*Зуева Надежда (ФИВТ 3 курс)*

#### При подготовке ноутбука использовался сайт: http://www.inp.nsk.su/~grozin/python/

<img align=center src="http://www.wizdomhub.com/wp-content/uploads/2017/08/numpy_project_page.jpg" style="height:160px;" />

---

Пакет `numpy`(НамПай) предоставляет $n$-мерные однородные массивы (все элементы одного типа); в них нельзя вставить или удалить элемент в произвольном месте. В `numpy` реализовано много операций над массивами в целом. Если задачу можно решить, произведя некоторую последовательность операций над массивами, то это будет столь же эффективно, как в `C` или `matlab` - львиная доля времени тратится в библиотечных функциях, написанных на `C`.

## Одномерные массивы

In [1]:
from numpy import (array,zeros,ones,arange,linspace,logspace,
                   float64,int64,sin,cos,pi,exp,log,sqrt,abs,
                   nan,inf,any,all,sort,hstack,vstack,hsplit,
                   delete,insert,append,eye,fromfunction,
                   trace,diag,average,std,outer,meshgrid)

Можно преобразовать список в массив.

In [2]:
a = array([3, 4, 1])
a, type(a)

(array([3, 4, 1]), numpy.ndarray)

`print` печатает массивы в удобной форме.

In [3]:
print(a)

[3 4 1]


Класс `ndarray` имеет много методов.

In [4]:
set(dir(a)) - set(dir(object))

{'T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_wrap__',
 '__bool__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delitem__',
 '__divmod__',
 '__float__',
 '__floordiv__',
 '__getitem__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__len__',
 '__lshift__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__neg__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__rfloordiv__',
 '__rlshift__',
 '__rmatmul__',
 '__rmod__',
 '__rmul__',
 '__ror__',
 '__rpow__',
 '__rrshift__',
 '__rshift__',
 '__rsub__',
 '__rtruediv__',
 '__rxor__',
 '__setitem__',
 '__setstate__',
 '__sub__',
 '__truediv__',
 '__xor__',
 'all',
 'any',

Наш массив одномерный.

In [5]:
a.ndim

1

In [6]:
print(a)

[3 4 1]


В $n$-мерном случае возвращается кортеж размеров по каждой координате.

ndarray.ndim — число осей (измерений) массива. Как уже было сказано, в мире Python число измерений часто называют рангом.

ndarray.shape — размеры массива, его форма. Это кортеж натуральных чисел, показывающий длину массива по каждой оси. Для матрицы из n строк и m столбов, shape будет (n,m). 



In [7]:
a.shape

(3,)

In [8]:
len(a), a.size

(3, 3)

#### Вопрос
Как связаны элементы кортежа shape, ndim, size?

`numpy` предоставляет несколько типов для целых (`int16`, `int32`, `int64`) и чисел с плавающей точкой (`float32`, `float64`).

In [9]:
a.dtype, a.dtype.name, a.itemsize

(dtype('int32'), 'int32', 4)

Массивы - изменяемые объекты, в отличие от кортежей

In [10]:
a[1] = 3
print(a)

[3 3 1]


Массивы, разумеется, можно использовать в `for` циклах. Но при этом теряется главное преимущество `numpy` - быстродействие. Всегда, когда это возможно, лучше использовать операции над массивами как едиными целыми.

In [11]:
%%time
for i in a:
    print(i)

3
3
1
Wall time: 1 ms


In [12]:
%%time
print(a)

[3 3 1]
Wall time: 0 ns


Массив чисел с плавающей точкой.

In [13]:
b = array([0., 2, 1])
b.dtype

dtype('float64')

Точно такой же массив.

In [14]:
c = array([0, 2, 1], dtype=float64)
print(c)

[ 0.  2.  1.]


Преобразование данных

In [15]:
print(c.dtype)
print(c.astype(int))
print(c.astype(str))

float64
[0 2 1]
['0.0' '2.0' '1.0']


Массив, значения которого вычисляются функцией. Функции передаётся массив. Так что в ней можно использовать только такие операции, которые применимы к массивам.

In [16]:
def f(i):
    print(i)
    return i ** 2

a = fromfunction(f, (5,), dtype=int64)
print(a)

[0 1 2 3 4]
[ 0  1  4  9 16]


In [17]:
a = fromfunction(f, (5,), dtype=float64)
print(a)

[ 0.  1.  2.  3.  4.]
[  0.   1.   4.   9.  16.]


Массивы, заполненные нулями или единицами. Часто лучше сначала создать такой массив, а потом присваивать значения его элементам.

In [18]:
a = zeros(3)
print(a)

[ 0.  0.  0.]


In [19]:
b = ones(3, dtype=int64)
print(b)

[1 1 1]


Если нужно создать массив, заполненный нулями, длины другого массива, то можно использовать конструкцию

Чтобы не писать отдельно включение каждой функции, можно написать сразу:

In [20]:
import numpy as np

In [21]:
np.zeros_like(b)

array([0, 0, 0], dtype=int64)

Функция `arange` подобна `range`. Аргументы могут быть с плавающей точкой. Следует избегать ситуаций, когда $(конец-начало)/шаг$ - целое число, потому что в этом случае включение последнего элемента зависит от ошибок округления. Лучше, чтобы конец диапазона был где-то посредине шага.

In [22]:
a = np.arange(0, 9, 2)
print(a)

[0 2 4 6 8]


In [23]:
b = np.arange(0., 9, 2)
print(b)

[ 0.  2.  4.  6.  8.]



Последовательности чисел с постоянным шагом можно также создавать функцией `linspace`. Начало и конец диапазона включаются; последний аргумент - число точек.

In [24]:
a = np.linspace(0, 8, 5)
print(a)

[ 0.  2.  4.  6.  8.]


In [25]:
a = np.linspace(0, 0.1, 5)
print(a)

[ 0.     0.025  0.05   0.075  0.1  ]


Массив случайных чисел (из непрерывного равномерного распределения).

In [26]:
print(np.random.random(5))

[ 0.75946853  0.07367264  0.64087708  0.48740112  0.41714419]


Случайные числа с нормальным (гауссовым) распределением (среднее `0`, среднеквадратичное отклонение `1`).

In [27]:
print(np.random.normal(size=5))

[ 0.91902923 -0.2314802   1.28862284 -0.83457516 -0.48425008]


## Операции над одномерными массивами

Арифметические операции проводятся поэлементно.

In [28]:
print(a + b)

[ 0.     2.025  4.05   6.075  8.1  ]


In [29]:
print(a - b)

[ 0.    -1.975 -3.95  -5.925 -7.9  ]


In [30]:
print(a * b)

[ 0.    0.05  0.2   0.45  0.8 ]


In [31]:
print(a / (b + 1))

[ 0.          0.00833333  0.01        0.01071429  0.01111111]


In [32]:
print(a ** 2)

[ 0.        0.000625  0.0025    0.005625  0.01    ]


Когда операнды разных типов, они пpиводятся к большему типу.

In [33]:
i = np.ones(5, dtype=np.int64)
print(a + i)

[ 1.     1.025  1.05   1.075  1.1  ]


`numpy` содержит элементарные функции, которые тоже применяются к массивам поэлементно. Они называются универсальными функциями (`ufunc`).

In [34]:
np.sin, type(np.sin)

(<ufunc 'sin'>, numpy.ufunc)

In [35]:
print(np.sin(a))
print(np.cosh(a))

[ 0.          0.0249974   0.04997917  0.07492971  0.09983342]
[ 1.          1.00031252  1.00125026  1.00281382  1.00500417]


Один из операндов может быть скаляром, а не массивом.

In [36]:
print(a + 1)

[ 1.     1.025  1.05   1.075  1.1  ]


In [37]:
print(2 * a)

[ 0.    0.05  0.1   0.15  0.2 ]


Сравнения дают булевы массивы.

In [38]:
print(a > b)

[False False False False False]


In [39]:
print(a == b)

[ True False False False False]


In [40]:
c = a > 5
print(c)

[False False False False False]


Кванторы "существует" и "для всех".

In [41]:
np.any(c), np.all(c)

(False, False)

Модификация на месте.

In [42]:
a += 1
print(a)

[ 1.     1.025  1.05   1.075  1.1  ]


In [43]:
b *= 2
print(b)

[  0.   4.   8.  12.  16.]


In [44]:
b /= a
print(b)

[  0.           3.90243902   7.61904762  11.1627907   14.54545455]


При выполнении операций над массивами деление на 0 не возбуждает исключения, а даёт значения `np.nan` или `np.inf`.

In [46]:
np.nan + 1, np.inf + 1, np.inf * 0, 1. / np.inf

(nan, inf, nan, 0.0)

Сумма и произведение всех элементов массива; максимальный и минимальный элемент; среднее и среднеквадратичное отклонение.

In [47]:
b.sum(), b.prod(), b.max(), b.min(), b.mean(), b.std()

(37.229731886566825,
 0.0,
 14.545454545454545,
 0.0,
 7.4459463773133647,
 5.1428877838280656)

In [57]:
x = np.random.normal(size=1000)
x.mean(), x.std()

(0.025217698244229744, 1.0417376679352235)

Имеются встроенные функции

In [58]:
print(np.sqrt(b))
print(np.exp(b))
print(np.log(b + 1))
print(np.sin(b))
print(np.e, np.pi)

[ 0.          1.97545919  2.76026224  3.34107628  3.81385036]
[  1.00000000e+00   4.95230899e+01   2.03662157e+03   7.04593127e+04
   2.07496438e+06]
[ 0.          1.58973284  2.15397459  2.49838135  2.74376828]
[ 0.         -0.68953468  0.9725297  -0.98605188  0.91780205]
2.718281828459045 3.141592653589793


Иногда бывает нужно использовать частичные (кумулятивные) суммы. В нашем курсе такое пригодится.

In [59]:
print(b.cumsum()[::-1])

[ 37.22973189  22.68427734  11.52148664   3.90243902   0.        ]


Функция `sort` возвращает отсортированную копию, метод `sort` сортирует на месте.

In [60]:
print(np.sort(b))
print(b)

[  0.           3.90243902   7.61904762  11.1627907   14.54545455]
[  0.           3.90243902   7.61904762  11.1627907   14.54545455]


In [61]:
b.sort()
print(b)

[  0.           3.90243902   7.61904762  11.1627907   14.54545455]


Объединение массивов "по-горизонтали" (horizontal stack).

In [62]:
a = np.array([1, 2, 3])
b = np.array([100, 200, 300])

print(np.hstack((a, b)))

[  1   2   3 100 200 300]


Объединение массивов "по-вертикали" (vertical stack).

In [63]:
print(np.vstack((a, b)))

[[  1   2   3]
 [100 200 300]]


Расщепление массива в позициях 3 и 6.

In [64]:
a = np.random.random(10)
np.hsplit(a, [3, 6])

[array([ 0.72884465,  0.56465046,  0.97346822]),
 array([ 0.99250212,  0.61086674,  0.95376611]),
 array([ 0.25972812,  0.17796181,  0.30903548,  0.39001284])]

Функции `delete`, `insert` и `append` не меняют массив на месте, а возвращают новый массив, в котором удалены, вставлены в середину или добавлены в конец какие-то элементы.

In [65]:
a = np.arange(10)

In [66]:
a = np.delete(a, [5, 7])
print(a)

[0 1 2 3 4 6 8 9]


In [67]:
a = np.insert(a, 2, [0, 0])
print(a)

[0 1 0 0 2 3 4 6 8 9]


In [68]:
a = np.append(a, [1, 2, 3])
print(a)

[0 1 0 0 2 3 4 6 8 9 1 2 3]


Есть несколько способов индексации массива. Вот обычный индекс.

In [69]:
a = np.linspace(0, 1, 11)
print(a)

[ 0.   0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1. ]


In [70]:
b = a[2]
print(b)

0.2


Диапазон индексов. Создаётся новый заголовок массива, указывающий на те же данные. Изменения, сделанные через такой массив, видны и в исходном массиве.

In [71]:
b = a[2:6]
print(b)

[ 0.2  0.3  0.4  0.5]


In [72]:
b[0] = -0.2
print(b)

[-0.2  0.3  0.4  0.5]


In [73]:
print(a)

[ 0.   0.1 -0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1. ]


Диапазон с шагом 2.

In [74]:
b = a[1:10:2]
print(b)

[ 0.1  0.3  0.5  0.7  0.9]


In [75]:
b[0] = -0.1
print(a)

[ 0.  -0.1 -0.2  0.3  0.4  0.5  0.6  0.7  0.8  0.9  1. ]


Массив в обратном порядке.

In [76]:
b = a[len(a):0:-1]
print(b)

[ 1.   0.9  0.8  0.7  0.6  0.5  0.4  0.3 -0.2 -0.1]


Подмассиву можно присвоить значение - массив правильного размера или скаляр.

In [77]:
a[1:10:3] = 0
print(a)

[ 0.   0.  -0.2  0.3  0.   0.5  0.6  0.   0.8  0.9  1. ]


Тут опять создаётся только новый заголовок, указывающий на те же данные.

In [78]:
b = a[:]
b[1] = 0.1
print(a)

[ 0.   0.1 -0.2  0.3  0.   0.5  0.6  0.   0.8  0.9  1. ]


Чтобы скопировать и данные массива, нужно использовать метод `copy`.

In [79]:
b = a.copy()
b[2] = 0
print(b)
print(a)

[ 0.   0.1  0.   0.3  0.   0.5  0.6  0.   0.8  0.9  1. ]
[ 0.   0.1 -0.2  0.3  0.   0.5  0.6  0.   0.8  0.9  1. ]


Можно задать список индексов.

In [80]:
print(a[[2, 3, 5]])

[-0.2  0.3  0.5]


Можно задать булев массив той же величины.

In [81]:
b = a > 0
print(b)

[False  True False  True False  True  True False  True  True  True]


In [82]:
print(a[b])

[ 0.1  0.3  0.5  0.6  0.8  0.9  1. ]


## 2-мерные массивы

In [83]:
a = np.array([[0.0, 1.0], [-1.0, 0.0]])
print(a)

[[ 0.  1.]
 [-1.  0.]]


In [84]:
a.ndim

2

In [85]:
a.shape

(2, 2)

In [86]:
len(a), a.size

(2, 4)

In [87]:
a[1, 0]

-1.0

Атрибуту `shape` можно присвоить новое значение - кортеж размеров по всем координатам. Получится новый заголовок массива; его данные не изменятся.

In [88]:
b = np.linspace(0, 3, 4)
print(b)

[ 0.  1.  2.  3.]


In [89]:
b.shape

(4,)

In [90]:
b.shape = 2, 2
print(b)

[[ 0.  1.]
 [ 2.  3.]]


Можно растянуть в одномерный массив

In [91]:
print(b.ravel())

[ 0.  1.  2.  3.]


Арифметические операции поэлементные

In [92]:
print(a + 1)
print(a * 2)
print(a + [0, 1])  # второе слагаемое дополняется до матрицы копированием строк
print(a + np.array([[0, 2]]).T)  # .T - транспонирование
print(a + b)

[[ 1.  2.]
 [ 0.  1.]]
[[ 0.  2.]
 [-2.  0.]]
[[ 0.  2.]
 [-1.  1.]]
[[ 0.  1.]
 [ 1.  2.]]
[[ 0.  2.]
 [ 1.  3.]]


Поэлементное и матричное (только в Python 3.5) умножение.

In [96]:
print(a)
print(b)

[[ 0.  1.]
 [-1.  0.]]
[[ 0.  1.]
 [ 2.  3.]]


In [93]:
print(a * b)

[[ 0.  1.]
 [-2.  0.]]


In [94]:
print(a @ b)

[[ 2.  3.]
 [ 0. -1.]]


In [95]:
print(b @ a)

[[-1.  0.]
 [-3.  2.]]


Умножение матрицы на вектор.

In [97]:
v = np.array([1, -1], dtype=np.float64)
print(b @ v)

[-1. -1.]


In [98]:
print(v @ b)

[-2. -2.]


Если у вас Питон более ранней версии, то для работы с матрицами можно использовать класс `np.matrix`, в котором операция умножения реализуется как матричное умножение.

In [99]:
np.matrix(a) * np.matrix(b)

matrix([[ 2.,  3.],
        [ 0., -1.]])

Внешнее произведение $a_{ij}=u_i v_j$

In [100]:
u = np.linspace(1, 2, 2)
v = np.linspace(2, 4, 3)
print(u)
print(v)

[ 1.  2.]
[ 2.  3.  4.]


In [101]:
a = np.outer(u, v)
print(a)

[[ 2.  3.  4.]
 [ 4.  6.  8.]]


Двумерные массивы, зависящие только от одного индекса: $x_{ij}=u_j$, $y_{ij}=v_i$

In [102]:
x, y = np.meshgrid(u, v)
print(x)
print(y)

[[ 1.  2.]
 [ 1.  2.]
 [ 1.  2.]]
[[ 2.  2.]
 [ 3.  3.]
 [ 4.  4.]]


Единичная матрица.

In [103]:
I = np.eye(4)
print(I)

[[ 1.  0.  0.  0.]
 [ 0.  1.  0.  0.]
 [ 0.  0.  1.  0.]
 [ 0.  0.  0.  1.]]


Метод `reshape` делает то же самое, что присваивание атрибуту `shape`.

In [104]:
print(I.reshape(16))

[ 1.  0.  0.  0.  0.  1.  0.  0.  0.  0.  1.  0.  0.  0.  0.  1.]


In [105]:
print(I.reshape(2, 8))

[[ 1.  0.  0.  0.  0.  1.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  1.]]


Строка.

In [106]:
print(I[1])

[ 0.  1.  0.  0.]


Цикл по строкам.

In [107]:
for row in I:
    print(row)

[ 1.  0.  0.  0.]
[ 0.  1.  0.  0.]
[ 0.  0.  1.  0.]
[ 0.  0.  0.  1.]


Столбец.

In [108]:
print(I[:, 2])

[ 0.  0.  1.  0.]


Подматрица.

In [109]:
print(I[0:2, 1:3])

[[ 0.  0.]
 [ 1.  0.]]


Можно построить двумерный массив из функции.

In [110]:
def f(i, j):
    print(i)
    print(j)
    return 10 * i + j

print(np.fromfunction(f, (4, 4), dtype=np.int64))

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]]
[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[[ 0  1  2  3]
 [10 11 12 13]
 [20 21 22 23]
 [30 31 32 33]]


Транспонированная матрица.

In [111]:
print(b.T)

[[ 0.  2.]
 [ 1.  3.]]


Соединение матриц по горизонтали и по вертикали.

In [112]:
a = np.array([[0, 1], [2, 3]])
b = np.array([[4, 5, 6], [7, 8, 9]])
c = np.array([[4, 5], [6, 7], [8, 9]])
print(a)
print(b)
print(c)

[[0 1]
 [2 3]]
[[4 5 6]
 [7 8 9]]
[[4 5]
 [6 7]
 [8 9]]


In [113]:
print(np.hstack((a, b)))

[[0 1 4 5 6]
 [2 3 7 8 9]]


In [114]:
print(np.vstack((a, c)))

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


Сумма всех элементов; суммы столбцов; суммы строк.

In [115]:
print(b.sum())
print(b.sum(axis=0))
print(b.sum(axis=1))

39
[11 13 15]
[15 24]


Аналогично работают `prod`, `max`, `min` и т.д.

In [116]:
print(b.max())
print(b.max(axis=0))
print(b.min(axis=1))

9
[7 8 9]
[4 7]


След - сумма диагональных элементов.

In [117]:
np.trace(a)

3

## Многомерные массивы
опциональный материал

In [118]:
X = np.arange(24).reshape(2, 3, 4)
print(X)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


Суммирование (аналогично остальные операции)

In [119]:
# суммируем только по нулевой оси, то есть для фиксированных j и k суммируем только элементы с индексами (*, j, k)
print(X.sum(axis=0))
# суммируем сразу по двум осям, то есть для фиксированной i суммируем только элементы с индексами (i, *, *)
print(X.sum(axis=(1, 2)))

[[12 14 16 18]
 [20 22 24 26]
 [28 30 32 34]]
[ 66 210]












## Линейная алгебра

In [120]:
np.linalg.det(a)

-2.0

Обратная матрица.

In [121]:
a1 = np.linalg.inv(a)
print(a1)

[[-1.5  0.5]
 [ 1.   0. ]]


In [122]:
print(a @ a1)
print(a1 @ a)

[[ 1.  0.]
 [ 0.  1.]]
[[ 1.  0.]
 [ 0.  1.]]


Решение линейной системы $au=v$.

In [123]:
v = np.array([0, 1], dtype=np.float64)
print(a1 @ v)

[ 0.5  0. ]


In [124]:
u = np.linalg.solve(a, v)
print(u)

[ 0.5  0. ]


Проверим.

In [125]:
print(a @ u - v)

[ 0.  0.]


Собственные значения и собственные векторы: $a u_i = \lambda_i u_i$. `l` - одномерный массив собственных значений $\lambda_i$, столбцы матрицы $u$ - собственные векторы $u_i$.

In [126]:
l, u = np.linalg.eig(a)
print(l)

[-0.56155281  3.56155281]


In [127]:
print(u)

[[-0.87192821 -0.27032301]
 [ 0.48963374 -0.96276969]]


Проверим.

In [128]:
for i in range(2):
    print(a @ u[:, i] - l[i] * u[:, i])

[  0.00000000e+00   1.66533454e-16]
[  0.00000000e+00  -4.44089210e-16]


Функция `diag` от одномерного массива строит диагональную матрицу; от квадратной матрицы - возвращает одномерный массив её диагональных элементов.

In [129]:
L = np.diag(l)
print(L)
print(np.diag(L))

[[-0.56155281  0.        ]
 [ 0.          3.56155281]]
[-0.56155281  3.56155281]


Все уравнения $a u_i = \lambda_i u_i$ можно собрать в одно матричное уравнение $a u = u \Lambda$, где $\Lambda$ - диагональная матрица с собственными значениями $\lambda_i$ на диагонали.

In [130]:
print(a @ u - u @ L)

[[  0.00000000e+00   0.00000000e+00]
 [  1.66533454e-16  -4.44089210e-16]]


Поэтому $u^{-1} a u = \Lambda$.

In [131]:
print(np.linalg.inv(u) @ a @ u)

[[ -5.61552813e-01   2.77555756e-17]
 [ -2.22044605e-16   3.56155281e+00]]


Найдём теперь левые собственные векторы $v_i a = \lambda_i v_i$ (собственные значения $\lambda_i$ те же самые).

In [132]:
l, v = np.linalg.eig(a.T)
print(l)
print(v)

[-0.56155281  3.56155281]
[[-0.96276969 -0.48963374]
 [ 0.27032301 -0.87192821]]


Собственные векторы нормированы на 1.

In [133]:
print(u.T @ u)
print(v.T @ v)

[[ 1.         -0.23570226]
 [-0.23570226  1.        ]]
[[ 1.          0.23570226]
 [ 0.23570226  1.        ]]


Левые и правые собственные векторы, соответствующие разным собственным значениям, ортогональны, потому что $v_i a u_j = \lambda_i v_i u_j = \lambda_j v_i u_j$.

In [134]:
print(v.T @ u)

[[  9.71825316e-01   0.00000000e+00]
 [ -5.55111512e-17   9.71825316e-01]]


# Интегрирование

In [135]:
from scipy.integrate import quad, odeint
from scipy.special import erf

In [136]:
def f(x):
    return np.exp(-x ** 2)

Адаптивное численное интегрирование (может быть до бесконечности). `err` - оценка ошибки.

In [137]:
res, err = quad(f, 0, np.inf)
print(np.sqrt(np.pi) / 2, res, err)

0.886226925453 0.8862269254527579 7.101318390915439e-09


In [138]:
res, err =  quad(f, 0, 1)
print(np.sqrt(np.pi) / 2 * erf(1), res, err)

0.746824132812 0.7468241328124271 8.291413475940725e-15


## Сохранение в файл и чтение из файла

In [139]:
x = np.arange(0, 25, 0.5).reshape((5, 10))

# Сохраняем в файл example.txt данные x в формате с двумя точками после запятой и разделителем ';'
np.savetxt('example.txt', x, fmt='%.2f', delimiter=';')

Получится такой файл

In [140]:
!cat example.txt

'cat' is not recognized as an internal or external command,
operable program or batch file.
